#!/usr/bin/env sh

yabai -m config layout bsp
# yabai -m config auto_balance on

# set focus follows mouse mode (default: off, options: off, autoraise, autofocus)
# TODO: makes popups disappear
# yabai -m config focus_follows_mouse autofocus
# yabai -m config focus_follows_mouse autoraise

# floating windows are always on top (default: off)
# yabai -m config window_topmost on

yabai -m config top_padding 5
yabai -m config bottom_padding 5
yabai -m config left_padding 5
yabai -m config right_padding 5
yabai -m config window_gap 5

yabai -m rule --add app="^System Settings$" sticky=on manage=off
yabai -m rule --add app="^Disk Utility$" sticky=on manage=off
yabai -m rule --add app="^System Information$" sticky=on manage=off
yabai -m rule --add app="^Activity Monitor$" sticky=on manage=off
yabai -m rule --add app="^tiimo$" sticky=on manage=off
yabai -m rule --add app="^Structured$" sticky=on manage=off
