[aws]
disabled = true

[directory]
truncate_to_repo = false
truncation_symbol = "…/"

[docker_context]
disabled = true

[gcloud]
disabled = true

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style) "

[golang]
disabled = true
